#!/usr/bin/env bash
# load balanecer haproxy install
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxyORIGINAL.cfg
cat >> /etc/haproxy/haproxy.cfg << EOF
    listen webapp 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 3645-web-01 3.234.214.251 check
    server 3645-web-02 34.204.189.222 check
EOF
service haproxy restart
