#!usr/bin/env bash
# setup ufw to allow ssh, http and https and block all other traffic

sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable -y
sudo ufw status
